### ISSUE TITLE
PageLoadException relating to Redis Cache

### ISSUE THREAD

**Issue by eddycrompton** [davidjrh/dnn.rediscachingprovider#1]
Getting multiple EventLog errors as follows:

DotNetNuke.Services.Exceptions.PageLoadException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list. ---> System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(String format, Object arg0, Object arg1)
   at DotNetNuke.Providers.RedisCachingProvider.RedisCachingProvider.ProcessException(Exception e, String key, Object value)
   at DotNetNuke.Providers.RedisCachingProvider.RedisCachingProvider.Insert(String key, Object value, DNNCacheDependency dependency, DateTime absoluteExpiration, TimeSpan slidingExpiration, CacheItemPriority priority, CacheItemRemovedCallback onRemoveCallback)
   at DotNetNuke.Common.Utilities.DataCache.SetCache(String CacheKey, Object objObject, DNNCacheDependency objDependency, DateTime AbsoluteExpiration, TimeSpan SlidingExpiration, CacheItemPriority Priority, CacheItemRemovedCallback OnRemoveCallback)
   at DotNetNuke.Common.Utilities.DataCache.SetCache(String CacheKey, Object objObject, TimeSpan SlidingExpiration)
   at DotNetNuke.UI.WebControls.CaptchaControl.GetNextCaptcha()
   at DotNetNuke.UI.WebControls.CaptchaControl.SaveViewState()
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Control.SaveViewStateRecursive(ViewStateMode inheritedMode)
   at System.Web.UI.Page.SaveAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   --- End of inner exception stack trace ---

**Comment by davidjrh** [comment]
This seems to be related to the commit af5e70523310898b3ec33e54f7e2afb6758e344b For some reason I did not upload the new 1.0.1 package to the Release folder. It's already there now, so just download and update.
